Full app
brytebee/Math-Magicians pull request #5
Opened 2021-12-01 14:36 UTC by brytebee

## React Routing 🌍💻 
In the PR, I have achieved the following:
- added multiple pages to the web app
- installed and implemented react routing
- added navbar and footer
- styled newly added components

2021-12-01 14:46 UTC, mikenath223 requested changes
Hello @brytebee 

You've done pretty well so far!
But for a few issues, you are almost done with this. Hang in there!


## Required Changes ♻️
_Please check the comments under the review._


Happy coding, Cheers! 🚀🚀

Do feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, whether it is valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-12-01 14:47 UTC, mikenath223 commented on src/App.js
> +      <Route path="/calculator" element={<Calculator />} />
- [ ] Kindly deploy the project online and include the live link in the readme.

2021-12-01 17:22 UTC, D4nielJ commented
## Hello @brytebee, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉

![](https://c.tenor.com/nJ3EeUPhVKkAAAAC/barny-stinson.gif)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear or you can always find me on slack!

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-12-02 09:35 UTC, brytebee commented
Hello, @ 👋👋,

Thanks for the warm-hearted review 👀👀.

![](https://media.giphy.com/media/a4jVHNk0ksgup1ILT6/giphy.gif)

I'll go ahead to merge and move on to the next milestone 🏁🏁.

**_Happy Hacking 😄😄_**

2021-12-02 09:36 UTC, merged